window.ENV = {
    FIREBASE_API_KEY: "YOUR_API_KEY",
    FIREBASE_AUTH_DOMAIN: "YOUR_DOMAIN",
    FIREBASE_PROJECT_ID: "YOUR_PROJECT_ID",
    FIREBASE_STORAGE_BUCKET: "YOUR_STORAGE_BUCKET",
    FIREBASE_MESSAGING_SENDER_ID: "YOUR_SENDER_ID",
    FIREBASE_APP_ID: "YOUR_APP_ID",
    FIREBASE_MEASUREMENT_ID: "YOUR_MEASUREMENT_ID",
    CLOUDINARY_CLOUD_NAME: "YOUR_CLOUD_NAME",
    CLOUDINARY_UPLOAD_PRESET: "YOUR_UPLOAD_PRESET"
};
